### ISSUE TITLE
Ошибка при запуске, старая версия в релизе.

### ISSUE THREAD

**Issue by junkees** [Keller18306/musicFromVK#2]
Привет, при запуске 
`ts-node .`
появляется ошибка

`[SETUP] Для получения прав администратора напишите боту: /setup token
/home/danya/musicFromVK-0.1/node_modules/telegraf/lib/core/helpers/compact.js:11
    return Object.fromEntries(compactEntries);
                  ^
TypeError: Object.fromEntries is not a function
    at compactOptions (/home/danya/musicFromVK-0.1/node_modules/telegraf/lib/core/helpers/compact.js:11:19)
    at new ApiClient (/home/danya/musicFromVK-0.1/node_modules/telegraf/lib/core/network/client.js:208:45)
    at new Telegram (/home/danya/musicFromVK-0.1/node_modules/telegraf/lib/telegram.js:7:1)
    at new Telegraf (/home/danya/musicFromVK-0.1/node_modules/telegraf/lib/telegraf.js:44:25)
    at Object.<anonymous> (/home/danya/musicFromVK-0.1/bot.ts:10:19)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Module.m._compile (/usr/local/lib/node_modules/ts-node/src/index.ts:1459:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/usr/local/lib/node_modules/ts-node/src/index.ts:1462:12)
    at Module.load (internal/modules/cjs/loader.js:653:32)
`

Инструкция к последнему релизу неактуальна, переменные api_id, api_hash не вынесены в config.type.ts

**Comment by junkees** [comment]
Telegram для связи - @junkes

**Comment by Keller18306** [comment]
Можно скрином?

**Comment by junkees** [comment]
<img width="921" alt="image" src="https://user-images.githubusercontent.com/34445596/156051806-b85f7a60-fada-4020-ab38-cbcd35c6c5bb.png">

**Comment by junkees** [comment]
NodeJS - v10.19.0
Npm - 6.14.4

**Comment by Keller18306** [comment]
Обнови ноду

**Comment by junkees** [comment]
![image](https://user-images.githubusercontent.com/34445596/156319826-e4f7eee6-8ac8-48df-85da-35af337ec600.png)

**Comment by Keller18306** [comment]
Переустанови модули

**Comment by WapStyle** [comment]
При установке все проблемы решаются просто
https://docs.nodesource.com/nsolid/4.7/docs#installation
