### ISSUE TITLE
моя музыка

### ISSUE THREAD

**Issue by BenzFfffJfd** [Keller18306/musicFromVK#5]
моя музыка
C:\apipython\botdir\musicFromVK-0.1\node_modules\vk-io\lib\index.js:1633
                errors: (response.execute_errors || []).map((error) => (new ExecuteError(error)))
                                                        ^
ExecuteError: Code №29 - Rate limit reached
    at C:\apipython\botdir\musicFromVK-0.1\node_modules\vk-io\lib\index.js:1633:73
    at Array.map (<anonymous>)
    at ParallelSelectedWorker.execute (C:\apipython\botdir\musicFromVK-0.1\node_modules\vk-io\lib\index.js:1633:57)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 29,
  params: [],
  method: 'audio.get'
}

**Comment by Keller18306** [comment]
Лимит вк

**Comment by BenzFfffJfd** [comment]
и что делать?

**Comment by Keller18306** [comment]
Не использовать бота для массового использования. Он только для единоличного. И не использовать автореги

**Comment by BenzFfffJfd** [comment]
я только сам пользуюсь. Нажал моя музыка и крашится
Видимо надо смириться
